"""empty message

Revision ID: 1722b1b55731
Revises: cbca3e0d0c64
Create Date: 2021-01-08 13:20:02.649406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1722b1b55731'
down_revision = 'cbca3e0d0c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('create_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_comment_quesion_id_question', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comment_question_id_question'), 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('quesion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quesion_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_comment_question_id_question'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comment_quesion_id_question', 'question', ['quesion_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('question_id')
        batch_op.drop_column('create_date')

    # ### end Alembic commands ###
